<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DBManager\DBManager.csproj" />
    <ProjectReference Include="..\ModelManager\ModelManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="CiberModel.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>CiberModel.cs</LastGenOutput>
    </None>
    <None Update="Model1.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Model1.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="CiberModel.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CiberModel.tt</DependentUpon>
    </Compile>
    <Compile Update="Model1.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Model1.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
